/*
 * mugen_char.h — Runtime MUGEN Character Data Loader
 * 
 * Loads chardata.json (generated by mugen_to_engine.py) and provides:
 *   - MUGEN physics constants (yaccel, walk speeds, friction)
 *   - State definitions (which anim, which hitdefs, damage, hitstun)
 *   - Input-to-state mapping from CMD
 *   - Character size/scaling from CNS [Size]
 *
 * This keeps the engine MUGEN-agnostic at compile time.
 * All character-specific data is loaded from JSON at runtime.
 */

#ifndef MUGEN_CHAR_H
#define MUGEN_CHAR_H

#include "raylib.h"
#include <stdbool.h>

/* ── Constants ── */
#define MC_MAX_STATES      256
#define MC_MAX_HITDEFS     4
#define MC_MAX_SOUNDS      8
#define MC_MAX_NEXT_STATES 4
#define MC_MAX_INPUTS      16

/* ── MUGEN Physics Constants (from CNS [Velocity], [Movement]) ── */
typedef struct {
    float walkFwd;
    float walkBack;
    float runFwdX, runFwdY;
    float runBackX, runBackY;
    float jumpNeuX, jumpNeuY;
    float jumpFwdX;
    float jumpBackX;
    float yaccel;         /* gravity */
    float standFriction;
    float crouchFriction;
    int   airjumpNum;
    int   airjumpHeight;
} MCPhysics;

/* ── Character Size (from CNS [Size]) ── */
typedef struct {
    float xscale, yscale;
    float groundBack, groundFront;
    float height;
    float attackDist;
    float headPosX, headPosY;
    float midPosX, midPosY;
} MCSize;

/* ── Character Data (from CNS [Data]) ── */
typedef struct {
    int life;
    int power;
    int attack;
    int defence;
} MCData;

/* ── HitDef (from CNS state controllers) ── */
typedef struct {
    int   damage;
    int   guardDamage;
    char  animtype[16];   /* "Light", "Medium", "Hard", "Back", "Up" */
    float groundVelX, groundVelY;
    float airVelX, airVelY;
    int   pauseP1, pauseP2;
    int   groundHittime;
    int   groundSlidetime;
} MCHitDef;

/* ── State Definition (from CNS [Statedef N]) ── */
typedef struct {
    int    stateId;
    char   type;          /* 'S', 'C', 'A', 'U' */
    char   movetype;      /* 'A' (attack), 'I' (idle), 'H' (hit) */
    char   physics;       /* 'S', 'C', 'A', 'N', 'U' */
    int    anim;          /* MUGEN action ID */
    float  velsetX, velsetY;
    bool   hasVelset;
    int    ctrl;          /* 0 = no control, 1 = has control */
    
    MCHitDef hitdefs[MC_MAX_HITDEFS];
    int      hitdefCount;
    
    int    nextStates[MC_MAX_NEXT_STATES];
    int    nextStateCount;
} MCState;

/* ── Input Mapping (from CMD) ── */
typedef struct {
    char label[32];
    int  stateId;
} MCInputEntry;

/* ── Full Character ── */
typedef struct {
    char      name[64];
    MCPhysics physics;
    MCSize    size;
    MCData    data;
    
    MCState   states[MC_MAX_STATES];
    int       stateCount;
    
    MCInputEntry inputs[MC_MAX_INPUTS];
    int          inputCount;
    
    bool ready;
} MugenCharData;

/* ── API ── */
void MC_Load(MugenCharData* mc, const char* chardataPath);
const MCState* MC_FindState(const MugenCharData* mc, int stateId);
int MC_GetAnimForState(const MugenCharData* mc, int stateId);

/* ── Implementation ── */
#ifdef MUGEN_CHAR_IMPLEMENTATION

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

/* Minimal JSON helpers */
static const char* mc_skip_ws(const char* p) {
    while (*p && (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r')) p++;
    return p;
}

static const char* mc_skip_to(const char* p, char c) {
    while (*p && *p != c) p++;
    if (*p == c) p++;
    return p;
}

static const char* mc_read_string(const char* p, char* buf, int bufSize) {
    p = mc_skip_to(p, '"');
    int i = 0;
    while (*p && *p != '"' && i < bufSize - 1) {
        buf[i++] = *p++;
    }
    buf[i] = '\0';
    if (*p == '"') p++;
    return p;
}

static float mc_read_float(const char** pp) {
    const char* p = *pp;
    p = mc_skip_ws(p);
    char buf[32];
    int i = 0;
    while (*p && (isdigit(*p) || *p == '-' || *p == '.' || *p == 'e' || *p == 'E' || *p == '+') && i < 30) {
        buf[i++] = *p++;
    }
    buf[i] = '\0';
    *pp = p;
    return (float)atof(buf);
}

static int mc_read_int(const char** pp) {
    return (int)mc_read_float(pp);
}

/* Skip a complete JSON value (string, number, object, array, bool, null) */
static const char* mc_skip_value(const char* p) {
    p = mc_skip_ws(p);
    if (*p == '"') {
        p++;
        while (*p && *p != '"') { if (*p == '\\') p++; p++; }
        if (*p == '"') p++;
    } else if (*p == '{') {
        int d = 1; p++;
        while (*p && d > 0) { if (*p == '{') d++; else if (*p == '}') d--; p++; }
    } else if (*p == '[') {
        int d = 1; p++;
        while (*p && d > 0) { if (*p == '[') d++; else if (*p == ']') d--; p++; }
    } else {
        while (*p && *p != ',' && *p != '}' && *p != ']') p++;
    }
    return p;
}

/* Parse physics section */
static void mc_parse_physics(const char** pp, MCPhysics* phys) {
    const char* p = *pp;
    p = mc_skip_to(p, '{');
    
    while (*p && *p != '}') {
        p = mc_skip_ws(p);
        if (*p == '}') break;
        if (*p == ',') { p++; continue; }
        
        if (*p == '"') {
            char key[64];
            p = mc_read_string(p, key, sizeof(key));
            p = mc_skip_to(p, ':');
            p = mc_skip_ws(p);
            
            if (strcmp(key, "walk_fwd") == 0) phys->walkFwd = mc_read_float(&p);
            else if (strcmp(key, "walk_back") == 0) phys->walkBack = mc_read_float(&p);
            else if (strcmp(key, "yaccel") == 0) phys->yaccel = mc_read_float(&p);
            else if (strcmp(key, "stand_friction") == 0) phys->standFriction = mc_read_float(&p);
            else if (strcmp(key, "crouch_friction") == 0) phys->crouchFriction = mc_read_float(&p);
            else if (strcmp(key, "jump_fwd_x") == 0) phys->jumpFwdX = mc_read_float(&p);
            else if (strcmp(key, "jump_back_x") == 0) phys->jumpBackX = mc_read_float(&p);
            else if (strcmp(key, "airjump_num") == 0) phys->airjumpNum = mc_read_int(&p);
            else if (strcmp(key, "airjump_height") == 0) phys->airjumpHeight = mc_read_int(&p);
            else if (strcmp(key, "run_fwd") == 0) {
                /* array [x, y] */
                p = mc_skip_to(p, '[');
                p = mc_skip_ws(p);
                phys->runFwdX = mc_read_float(&p);
                p = mc_skip_to(p, ',');
                p = mc_skip_ws(p);
                phys->runFwdY = mc_read_float(&p);
                p = mc_skip_to(p, ']');
            }
            else if (strcmp(key, "run_back") == 0) {
                p = mc_skip_to(p, '[');
                p = mc_skip_ws(p);
                phys->runBackX = mc_read_float(&p);
                p = mc_skip_to(p, ',');
                p = mc_skip_ws(p);
                phys->runBackY = mc_read_float(&p);
                p = mc_skip_to(p, ']');
            }
            else if (strcmp(key, "jump_y") == 0) {
                p = mc_skip_to(p, '[');
                p = mc_skip_ws(p);
                phys->jumpNeuX = mc_read_float(&p);
                p = mc_skip_to(p, ',');
                p = mc_skip_ws(p);
                phys->jumpNeuY = mc_read_float(&p);
                p = mc_skip_to(p, ']');
            }
            else p = mc_skip_value(p);
        } else p++;
    }
    if (*p == '}') p++;
    *pp = p;
}

/* Parse a single state's hitdef array */
static void mc_parse_hitdefs(const char** pp, MCState* state) {
    const char* p = *pp;
    p = mc_skip_to(p, '[');
    
    while (*p && *p != ']' && state->hitdefCount < MC_MAX_HITDEFS) {
        p = mc_skip_ws(p);
        if (*p == ']') break;
        if (*p == ',') { p++; continue; }
        
        if (*p == '{') {
            p++;
            MCHitDef* hd = &state->hitdefs[state->hitdefCount];
            memset(hd, 0, sizeof(MCHitDef));
            
            while (*p && *p != '}') {
                p = mc_skip_ws(p);
                if (*p == '}' || *p == '\0') break;
                if (*p == ',') { p++; continue; }
                
                if (*p == '"') {
                    char key[64];
                    p = mc_read_string(p, key, sizeof(key));
                    p = mc_skip_to(p, ':');
                    p = mc_skip_ws(p);
                    
                    if (strcmp(key, "damage") == 0) hd->damage = mc_read_int(&p);
                    else if (strcmp(key, "guard_damage") == 0) hd->guardDamage = mc_read_int(&p);
                    else if (strcmp(key, "animtype") == 0) p = mc_read_string(p, hd->animtype, sizeof(hd->animtype));
                    else if (strcmp(key, "ground_hittime") == 0) hd->groundHittime = mc_read_int(&p);
                    else if (strcmp(key, "ground_slidetime") == 0) hd->groundSlidetime = mc_read_int(&p);
                    else if (strcmp(key, "pausetime") == 0) {
                        p = mc_skip_to(p, '[');
                        hd->pauseP1 = mc_read_int(&p);
                        p = mc_skip_to(p, ',');
                        hd->pauseP2 = mc_read_int(&p);
                        p = mc_skip_to(p, ']');
                    }
                    else if (strcmp(key, "ground_velocity") == 0) {
                        p = mc_skip_to(p, '[');
                        hd->groundVelX = mc_read_float(&p);
                        if (strchr(p, ',') && strchr(p, ',') < strchr(p, ']')) {
                            p = mc_skip_to(p, ',');
                            hd->groundVelY = mc_read_float(&p);
                        }
                        p = mc_skip_to(p, ']');
                    }
                    else if (strcmp(key, "air_velocity") == 0) {
                        p = mc_skip_to(p, '[');
                        hd->airVelX = mc_read_float(&p);
                        p = mc_skip_to(p, ',');
                        hd->airVelY = mc_read_float(&p);
                        p = mc_skip_to(p, ']');
                    }
                    else p = mc_skip_value(p);
                } else p++;
            }
            if (*p == '}') p++;
            state->hitdefCount++;
        } else p++;
    }
    if (*p == ']') p++;
    *pp = p;
}

/* Parse states object */
static void mc_parse_states(const char** pp, MugenCharData* mc) {
    const char* p = *pp;
    p = mc_skip_to(p, '{');
    
    while (*p && *p != '}' && mc->stateCount < MC_MAX_STATES) {
        p = mc_skip_ws(p);
        if (*p == '}') break;
        if (*p == ',') { p++; continue; }
        
        if (*p == '"') {
            char idBuf[16];
            p = mc_read_string(p, idBuf, sizeof(idBuf));
            int stateId = atoi(idBuf);
            
            p = mc_skip_to(p, ':');
            p = mc_skip_ws(p);
            
            if (*p == '{') {
                p++;
                MCState* s = &mc->states[mc->stateCount];
                memset(s, 0, sizeof(MCState));
                s->stateId = stateId;
                s->type = 'S';
                s->movetype = 'I';
                s->physics = 'S';
                s->anim = stateId;
                s->ctrl = -1;
                
                while (*p && *p != '}') {
                    p = mc_skip_ws(p);
                    if (*p == '}' || *p == '\0') break;
                    if (*p == ',') { p++; continue; }
                    
                    if (*p == '"') {
                        char key[32];
                        p = mc_read_string(p, key, sizeof(key));
                        p = mc_skip_to(p, ':');
                        p = mc_skip_ws(p);
                        
                        if (strcmp(key, "type") == 0) { char tmp[8]; p = mc_read_string(p, tmp, sizeof(tmp)); s->type = tmp[0]; }
                        else if (strcmp(key, "movetype") == 0) { char tmp[8]; p = mc_read_string(p, tmp, sizeof(tmp)); s->movetype = tmp[0]; }
                        else if (strcmp(key, "physics") == 0) { char tmp[8]; p = mc_read_string(p, tmp, sizeof(tmp)); s->physics = tmp[0]; }
                        else if (strcmp(key, "anim") == 0) s->anim = mc_read_int(&p);
                        else if (strcmp(key, "ctrl") == 0) s->ctrl = mc_read_int(&p);
                        else if (strcmp(key, "velset") == 0) {
                            p = mc_skip_to(p, '[');
                            s->velsetX = mc_read_float(&p);
                            p = mc_skip_to(p, ',');
                            s->velsetY = mc_read_float(&p);
                            p = mc_skip_to(p, ']');
                            s->hasVelset = true;
                        }
                        else if (strcmp(key, "hitdefs") == 0) mc_parse_hitdefs(&p, s);
                        else if (strcmp(key, "next_states") == 0) {
                            p = mc_skip_to(p, '[');
                            while (*p && *p != ']' && s->nextStateCount < MC_MAX_NEXT_STATES) {
                                p = mc_skip_ws(p);
                                if (*p == ']') break;
                                if (*p == ',') { p++; continue; }
                                s->nextStates[s->nextStateCount++] = mc_read_int(&p);
                            }
                            if (*p == ']') p++;
                        }
                        else if (strcmp(key, "sounds") == 0) p = mc_skip_value(p);
                        else p = mc_skip_value(p);
                    } else p++;
                }
                if (*p == '}') p++;
                mc->stateCount++;
            } else p = mc_skip_value(p);
        } else p++;
    }
    if (*p == '}') p++;
    *pp = p;
}

/* Parse input_map */
static void mc_parse_inputs(const char** pp, MugenCharData* mc) {
    const char* p = *pp;
    p = mc_skip_to(p, '{');
    
    while (*p && *p != '}' && mc->inputCount < MC_MAX_INPUTS) {
        p = mc_skip_ws(p);
        if (*p == '}') break;
        if (*p == ',') { p++; continue; }
        
        if (*p == '"') {
            MCInputEntry* inp = &mc->inputs[mc->inputCount];
            p = mc_read_string(p, inp->label, sizeof(inp->label));
            p = mc_skip_to(p, ':');
            inp->stateId = mc_read_int(&p);
            mc->inputCount++;
        } else p++;
    }
    if (*p == '}') p++;
    *pp = p;
}

/* Parse size section */
static void mc_parse_size(const char** pp, MCSize* sz) {
    const char* p = *pp;
    p = mc_skip_to(p, '{');
    
    while (*p && *p != '}') {
        p = mc_skip_ws(p);
        if (*p == '}') break;
        if (*p == ',') { p++; continue; }
        
        if (*p == '"') {
            char key[32];
            p = mc_read_string(p, key, sizeof(key));
            p = mc_skip_to(p, ':');
            p = mc_skip_ws(p);
            
            if (strcmp(key, "xscale") == 0) sz->xscale = mc_read_float(&p);
            else if (strcmp(key, "yscale") == 0) sz->yscale = mc_read_float(&p);
            else if (strcmp(key, "ground_back") == 0) sz->groundBack = mc_read_float(&p);
            else if (strcmp(key, "ground_front") == 0) sz->groundFront = mc_read_float(&p);
            else if (strcmp(key, "height") == 0) sz->height = mc_read_float(&p);
            else if (strcmp(key, "attack_dist") == 0) sz->attackDist = mc_read_float(&p);
            else if (strcmp(key, "head_pos") == 0) {
                p = mc_skip_to(p, '[');
                sz->headPosX = mc_read_float(&p);
                p = mc_skip_to(p, ',');
                sz->headPosY = mc_read_float(&p);
                p = mc_skip_to(p, ']');
            }
            else if (strcmp(key, "mid_pos") == 0) {
                p = mc_skip_to(p, '[');
                sz->midPosX = mc_read_float(&p);
                p = mc_skip_to(p, ',');
                sz->midPosY = mc_read_float(&p);
                p = mc_skip_to(p, ']');
            }
            else p = mc_skip_value(p);
        } else p++;
    }
    if (*p == '}') p++;
    *pp = p;
}

/* Parse data section */
static void mc_parse_data(const char** pp, MCData* d) {
    const char* p = *pp;
    p = mc_skip_to(p, '{');
    
    while (*p && *p != '}') {
        p = mc_skip_ws(p);
        if (*p == '}') break;
        if (*p == ',') { p++; continue; }
        
        if (*p == '"') {
            char key[32];
            p = mc_read_string(p, key, sizeof(key));
            p = mc_skip_to(p, ':');
            p = mc_skip_ws(p);
            
            if (strcmp(key, "life") == 0) d->life = mc_read_int(&p);
            else if (strcmp(key, "power") == 0) d->power = mc_read_int(&p);
            else if (strcmp(key, "attack") == 0) d->attack = mc_read_int(&p);
            else if (strcmp(key, "defence") == 0) d->defence = mc_read_int(&p);
            else p = mc_skip_value(p);
        } else p++;
    }
    if (*p == '}') p++;
    *pp = p;
}

/* ── Main load function ── */
void MC_Load(MugenCharData* mc, const char* chardataPath) {
    memset(mc, 0, sizeof(MugenCharData));
    
    /* Set defaults */
    mc->physics.yaccel = 0.44f;
    mc->physics.walkFwd = 1.5f;
    mc->physics.walkBack = -1.5f;
    mc->physics.jumpNeuY = -8.4f;
    mc->physics.standFriction = 0.85f;
    mc->physics.crouchFriction = 0.82f;
    mc->size.xscale = 1.0f;
    mc->size.yscale = 1.0f;
    mc->size.height = 60.0f;
    mc->data.life = 1000;
    mc->data.attack = 100;
    mc->data.defence = 100;
    
    char* json = LoadFileText(chardataPath);
    if (!json) {
        TraceLog(LOG_WARNING, "MC: Could not load %s", chardataPath);
        return;
    }
    
    const char* p = json;
    p = mc_skip_to(p, '{'); /* root object */
    
    while (*p && *p != '}') {
        p = mc_skip_ws(p);
        if (*p == '}') break;
        if (*p == ',') { p++; continue; }
        
        if (*p == '"') {
            char key[32];
            p = mc_read_string(p, key, sizeof(key));
            p = mc_skip_to(p, ':');
            p = mc_skip_ws(p);
            
            if (strcmp(key, "name") == 0) p = mc_read_string(p, mc->name, sizeof(mc->name));
            else if (strcmp(key, "physics") == 0) mc_parse_physics(&p, &mc->physics);
            else if (strcmp(key, "size") == 0) mc_parse_size(&p, &mc->size);
            else if (strcmp(key, "data") == 0) mc_parse_data(&p, &mc->data);
            else if (strcmp(key, "states") == 0) mc_parse_states(&p, mc);
            else if (strcmp(key, "input_map") == 0) mc_parse_inputs(&p, mc);
            else p = mc_skip_value(p);
        } else p++;
    }
    
    UnloadFileText(json);
    mc->ready = true;
    
    TraceLog(LOG_INFO, "MC: Loaded '%s' - %d states, %d inputs, yaccel=%.2f, walkFwd=%.1f",
             mc->name, mc->stateCount, mc->inputCount, mc->physics.yaccel, mc->physics.walkFwd);
}

const MCState* MC_FindState(const MugenCharData* mc, int stateId) {
    for (int i = 0; i < mc->stateCount; i++) {
        if (mc->states[i].stateId == stateId) return &mc->states[i];
    }
    return NULL;
}

int MC_GetAnimForState(const MugenCharData* mc, int stateId) {
    const MCState* s = MC_FindState(mc, stateId);
    return s ? s->anim : stateId;
}

#endif /* MUGEN_CHAR_IMPLEMENTATION */
#endif /* MUGEN_CHAR_H */
